[package]
name = "hive-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hive"
path = "hive-cli/src/main.rs"

[workspace]
members = ["hive-core"]

[dependencies]
hive-core = { path = "hive-core" }
