[package]
name = "hive-core"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.63"
erased-serde = "0.3.16"
futures = "0.3.17"
mlua = { version = "0.7.0", features = ["lua54", "send", "async", "macros"] }
once_cell = "1.9.0"
regex = "1.5.4"
serde = "1.0.132"
serde_json = "1.0.73"
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
