[package]
name = "hive-core"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
futures = "0.3.17"
mlua = { version = "0.7.0", features = ["lua54"] }
tokio = { version = "1.14.0", features = ["full"] }
uuid = "0.8.2"
