[package]
name = "hive-core"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.63"
dashmap = "5.0.0"
futures = "0.3.17"
hyper = "0.14.16"
mlua = { version = "0.7.0", features = ["lua54", "send", "async", "macros", "serialize"] }
once_cell = "1.9.0"
regex = "1.5.4"
serde = { version = "1.0.132", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.73"
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
